##### PREFLIGHT ########
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'heroku/brew'
tap 'mas-cli/tap'

### Special for fonts
brew 'svn'

##### FONTS #####
cask 'font-fira-code'
cask 'font-hack-nerd-font'
cask 'font-source-code-pro'

##### FORMULAES #####
brew 'ack'
brew 'apktool'
brew 'awscli'
brew 'bat'
brew 'binwalk'
brew 'cmatrix'
brew 'coreutils'
brew 'ctop'
brew 'curl', link: true
brew 'dive'
brew 'elixir'
brew 'exiftool'
brew 'exploitdb'
brew 'fd'
brew 'ffmpeg'
brew 'fzf'
brew 'gdb'
brew 'gh'
brew 'git'
brew 'go'
brew 'gobuster'
brew 'gotop'
brew 'gpg'
brew 'heroku'
brew 'htop'
brew 'imagemagick'
brew 'inetutils'
brew 'john-jumbo'
brew 'kubectl'
brew 'lua'
brew 'masscan'
brew 'n'
brew 'ncdu'
brew 'netcat'
brew 'nmap'
brew 'node'
brew 'nvim'
brew 'pinentry-mac'
brew 'pngcheck'
brew 'postgresql'
brew 'pre-commit'
brew 'pulseaudio'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'python3'
brew 'speedtest-cli'
brew 'rename'
brew 'ripgrep'
brew 'ruby'
brew 'rustup-init'
brew 'rust-analyzer'
brew 'showkey'
brew 'socat'
brew 'speedtest-cli'
brew 'sqlmap'
brew 'stow'
brew 'terraform-ls'
brew 'tfenv'
brew 'tldr'
brew 'tmux'
brew 'tor'
brew 'tree'
brew 'urlview'
brew 'vim'
brew 'wget'
brew 'youtube-dl'
brew 'zsh'

######## CASK ########
cask 'adobe-creative-cloud'
cask 'alfred'
cask 'android-file-transfer'
cask 'android-studio'
cask 'angry-ip-scanner'
cask 'anki'
cask 'audacity'
cask 'balenaetcher'
cask 'betterzip'
cask 'bloodhound'
cask 'burp-suite'
cask 'captin'
cask 'centered'
cask 'datagrip'
cask 'discord'
cask 'docker'
cask 'figma'
cask 'font-hack-nerd-font'
cask 'firefox-developer-edition'
cask 'flutter'
cask 'folx'
cask 'ghidra'
# cask 'google-chrome'
cask 'google-cloud-sdk'
cask 'google-drive'
cask 'hammerspoon'
cask 'http-toolkit'
cask 'istat-menus' # Actual Version ^6
cask 'iterm2'
cask 'little-snitch'
# cask 'metasploit' # Failing due to 404
cask 'micro-snitch'
cask 'mongodb-compass'
cask 'ngrok'
cask 'nordvpn'
cask 'nosql-workbench'
cask 'obsidian'
cask 'owasp-zap'
cask 'postman'
cask 'qlmarkdown'
cask 'removebg'
# cask 'sip'
# cask 'slack'
cask 'spotify'
cask 'telegram'
cask 'tor-browser'
cask 'tunnelblick'
cask 'visual-studio-code'
cask 'vlc'
cask 'whatsapp'
cask 'wireshark'
cask 'xquartz'
cask 'zoom'

####### Mac Application Store #########
mas 'Keynote', id: 409183694
mas 'Presentify - Screen Annotation', id: 1507246666
mas 'Spark – Email App by Readdle', id: 1176895641
mas 'GIPHY Capture. The GIF Maker', id: 668208984

####### LUXOR #######
brew 'automake'
brew 'berkeley-db@4'
brew 'boost'
brew 'miniupnpc'
cask 'linear-linear'

