##### PREFLIGHT ########
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'mas-cli/tap'

##### FONTS #####
cask 'font-fira-code'
cask 'font-source-code-pro'

##### FORMULAES #####
brew 'ack'
brew 'awscli'
brew 'aws-okta'
brew 'coreutils'
brew 'ctop'
brew 'curl', link: true
brew 'dive'
brew 'ffmpeg'
brew 'gh'
brew 'git'
brew 'go'
brew 'htop'
brew 'inetutils'
brew 'ispell'
brew 'lua'
brew 'ncdu'
brew 'node'
brew 'postgresql'
brew 'pre-commit'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'python3'
brew 'speedtest-cli'
brew 'terraform-ls'
brew 'tfenv'
brew 'the_silver_searcher'
brew 'tmux'
brew 'tree'
brew 'vim'
brew 'wget'
brew 'zsh'

######## CASK ########
cask 'alfred'
cask 'betterzip'
cask 'datagrip'
cask 'docker'
cask 'emacs'
cask 'figma'
cask 'google-backup-and-sync'
cask 'google-chrome'
cask 'hammerspoon'
cask 'iterm2'
cask 'obsidian'
cask 'postman'
cask 'slack'
cask 'visual-studio-code'
cask 'vlc'

####### Mac Application Store #########
mas 'Keynote', id: 409183694
mas 'Spark – Email App by Readdle', id: 1176895641 

