# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/Users/roeeyn/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="spaceship"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-autosuggestions zsh-syntax-highlighting docker)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

#####################################################
######## Aquí empieza el desvergue viejón! ##########
#####################################################

# For homebrew
export PATH="/opt/homebrew/bin:$PATH"

export SPACESHIP_CHAR_SYMBOL="🍺➜ "
export SPACESHIP_TIME_SHOW="true"
export SPACESHIP_EXIT_CODE_SHOW="true"

export LANG=en_US.UTF-8
set -o vi

alias gnp="git --no-pager"
alias gnpb="git --no-pager branch"
alias gnps="git --no-pager stash list"
alias rgi=rogit
alias rgim="rogit -m"
alias ktl=kubectl
alias dsr="docker stop $(docker ps | awk '{print $1}' | grep -v CONTAINER)"
alias hcr="heroku container:release web -a"
alias hcp="heroku container:push web -a"

# Para el flutter
# export PATH="$PATH:$HOME/Documents/flutter/bin"

# MMada de KLI de konfio
# . /usr/local/lib/python3.8/site-packages/kli/autocomplete.sh

# For FZF
if type rg &> /dev/null; then
  # export FZF_DEFAULT_COMMAND='ag'
  export FZF_DEFAULT_COMMAND='rg --files'
  # export FZF_DEFAULT_OPTS='-m --height 50% --border'
fi

# For pyenv
export PATH="$(pyenv root)/shims:/usr/local/bin:/usr/bin:/bin:$PATH"

# For pyenv virtual env
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
export PYENV_VIRTUALENV_DISABLE_PROMPT=1

# For virtualenvwrapper
export PATH="/usr/local/opt/python/libexec/bin:/usr/local/sbin:$PATH"
export PATH="/Users/roeeyn/Library/Python/3.8/bin:$PATH"
export PATH="/usr/local/bin:usr/local/share/python:$PATH"
# export WORKON_HOME="~/VirtualEnvs"
# source /Users/roeeyn/Library/Python/3.8/bin/virtualenvwrapper.sh
# export PYENV_VIRTUALENVWRAPPER_PREFER_PYVENV="true"

# For openssl error inside psycopg2 installation
# https://stackoverflow.com/a/62931654/7916568
# export LDFLAGS="-L/usr/local/opt/openssl/lib"
# export CPPFLAGS="-I/usr/local/opt/openssl/include"

# For john stuff
export PATH="$PATH:/usr/local/share/john"

# For ping and another brew commands
export PATH="/opt/homebrew/sbin:/opt/homebrew/bin:$PATH"

# For ruby stuff
export PATH="/usr/local/opt/ruby/bin:$PATH"
export PATH="/Users/roeeyn/.gem/ruby/2.7.0/bin:$PATH"

# export BYOBU_PREFIX=/usr/local
# export PATH=${PATH}:/.cargo/bin
# if command -v pyenv 1>/dev/null 2>&1; then
#   eval "$(pyenv init -)"
# fi
# export PATH="/usr/local/opt/scala@2.12/bin:$PATH"

# The next line updates PATH for the Google Cloud SDK.
source "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc"

source "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"

if [ ! "$TMUX" = "" ]; then export TERM=xterm-256color; fi

# For java 8
# export JAVA_HOME_8=$(/usr/libexec/java_home -v1.8)

# Java 8
# export JAVA_HOME=$JAVA_HOME_8
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"
