return {
    'folke/which-key.nvim',
    event = 'VeryLazy',
    opts = {
        -- your configuration comes here
        -- or leave it empty to use the default settings
        -- refer to the configuration section below
    },
    keys = {
        {
            '<leader>?',
            function()
                require('which-key').show { global = false }
            end,
            desc = 'Buffer Local Keymaps (which-key)',
        },
        { '<leader>b', group = 'Buffers' },
        { '<leader>bD', '<cmd>%bd|e#|bd#<cr>', desc = 'Close other buffers' },
        { '<leader>bb', '<cmd>Telescope buffers<cr>', desc = 'Telescope buffers' },
        { '<leader>bd', '<cmd>Bdelete<cr>', desc = 'Soft remove buffer' },
        { '<leader>bl', '<C-^>', desc = 'Last buffer' },
        { '<leader>bn', '<cmd>bn<cr>', desc = 'Next Buffer' },
        { '<leader>bp', '<cmd>bp<cr>', desc = 'Previous buffer' },
        { '<leader>bx', '<cmd>bd<cr>', desc = 'Hard remove buffer' },
        { '<leader>c', group = 'Code' },
        { '<leader>c0', '<cmd>lua require("conform").format()<cr>', desc = '[Format] Buffer' },
        { '<leader>cR', '<cmd>lua vim.lsp.buf.rename()<cr>', desc = '[LSP] Rename definition' },
        { '<leader>ca', '<cmd>lua vim.lsp.buf.code_action()<cr>', desc = '[LSP] Diagn. Action' },
        { '<leader>cc', '<cmd>cclose<cr>', desc = '[Quickfix] Close' },
        { '<leader>cd', '<cmd>lua vim.lsp.buf.declaration()<cr>', desc = '[LSP] Go To Declaration' },
        { '<leader>cf', 'lua require("nvim-comment-frame").add_comment()', desc = '[Comment] Frame one line' },
        { '<leader>cg', '<cmd>cc<cr>', desc = '[Quickfix] Go to current element' },
        { '<leader>cl', '<cmd>Telescope quickfix<cr>', desc = '[Quickfix] List quickfix elements' },
        { '<leader>cm', '<cmd>lua require("nvim-comment-frame").add_multiline_comment()<CR>', desc = '[Comment] Frame multiple lines' },
        { '<leader>cn', '<cmd>cnext<cr>', desc = '[Quickfix] Go to next element' },
        { '<leader>co', '<cmd>copen<cr>', desc = '[Quickfix] Open quickfix list' },
        { '<leader>cp', '<cmd>cprevious<cr>', desc = '[Quickfix] Go to prev element' },
        { '<leader>cs', '<cmd>lua vim.lsp.buf.signature_help()<cr>', desc = '[LSP] Signature help' },
        { '<leader>ct', '<cmd>lua require("hover").hover()<cr>', desc = '[LSP] Hover Info' },
        { '<leader>cx', '<cmd>lua vim.fn.setqflist({})<cr>', desc = '[Quickfix] Clear quickfix' },
        { '<leader>cy', 'yypk <cmd>CommentToggle<CR>j', desc = '[Misc] Duplicate and comment' },
        { '<leader>d', group = 'Debug/Diag.' },
        { '<leader>db', '<cmd>lua require"dap".toggle_breakpoint()<cr>', desc = '[Debug] Toggle Breakpoint' },
        { '<leader>dc', '<cmd>lua require"dap".continue()<cr>', desc = '[Debug] Start/Continue' },
        { '<leader>dd', '<cmd>Neogen<cr>', desc = '[Neogen] Generate Annotation' },
        { '<leader>dh', "<cmd>lua require'dap.ui.widgets'.hover()<cr>", desc = '[Debug] Hover' },
        { '<leader>dn', '<cmd>lua vim.diagnostic.goto_next()<cr>', desc = '[Diag] Go Next' },
        { '<leader>do', '<cmd>Trouble diagnostics toggle<cr>', desc = '[Trouble] Toggle diagnostics' },
        { '<leader>dp', '<cmd>lua vim.diagnostic.goto_prev()<cr>', desc = '[Diag] Go Prev' },
        { '<leader>dr', '<cmd>Trouble diagnostics refresh<cr>', desc = '[Trouble] Refresh diagnostics' },
        { '<leader>dB', '<cmd>Trouble diagnostics toggle filter.buf=0<cr>', desc = '[Trouble] Buffer diagnostics' },
        { '<leader>ds', group = 'Debugging' },
        { '<leader>dsd', '<cmd>lua require"dap".down()<cr>', desc = 'Down' },
        { '<leader>dsi', '<cmd>lua require"dap".step_into()<cr>', desc = 'Step into' },
        { '<leader>dso', '<cmd>lua require"dap".step_out()<cr>', desc = 'Step out' },
        { '<leader>dst', '<cmd>lua require"dap".stop()<cr>', desc = 'Stop' },
        { '<leader>dsu', '<cmd>lua require"dap".up()<cr>', desc = 'Up' },
        { '<leader>dsv', '<cmd>lua require"dap".step_over()<cr>', desc = 'Step over' },
        { '<leader>dt', group = 'Telescope DAP' },
        { '<leader>dtb', '<cmd>Telescope dap list_breakpoints<cr>', desc = '[DAP] List breakpoints' },
        { '<leader>dtc', '<cmd>Telescope dap commands<cr>', desc = '[DAP] List commands' },
        { '<leader>dtf', '<cmd>Telescope dap frames<cr>', desc = '[DAP] List frames' },
        { '<leader>dtv', '<cmd>Telescope dap variables<cr>', desc = '[DAP] List variables' },
        { '<leader>du', "<cmd>lua require'dapui'.()<CR>", desc = '[Debug] Toggle UI' },
        { '<leader>e', group = 'Errors' },
        { '<leader>eO', '<cmd>lua require("telescope.builtin").diagnostics{}<cr>', desc = 'Open diagnostics' },
        { '<leader>ec', '<cmd>lclose<cr>', desc = 'Close location list' },
        { '<leader>el', '<cmd>lua vim.diagnostic.open_float()<cr>', desc = 'Open diagnostic float' },
        { '<leader>en', '<cmd>lnext<cr>', desc = 'Next location list item' },
        { '<leader>eo', '<cmd>lua require("telescope.builtin").diagnostics{bufnr=0}<cr>', desc = 'Open current buffer diagnostics' },
        { '<leader>ep', '<cmd>lprevious<cr>', desc = 'Prev location list item' },
        { '<leader>f', group = 'File/Find/Telescope' },
        { '<leader>f/', '<cmd>Telescope current_buffer_fuzzy_find<cr>', desc = '[Telescope] Fuzzy search in buffer' },
        { '<leader>fS', '<cmd>wa<cr>', desc = '[File] Save all buffers' },
        { '<leader>fa', '<cmd>Telescope aerial<cr>', desc = '[Telescope] aerial (symbols)' },
        { '<leader>fb', '<cmd>Telescope builtin<cr>', desc = '[Telescope] builtin' },
        { '<leader>fc', '<cmd>Telescope quickfix<cr>', desc = '[Telescope] quickfix' },
        { '<leader>fe', '<cmd>Telescope symbols<cr>', desc = '[Telescope] emojis' },
        { '<leader>ff', '<cmd>Telescope find_files<cr>', desc = '[Telescope] Find file' },
        { '<leader>fg', '<cmd>Telescope grep_string<cr>', desc = '[Telescope] Grep string' },
        { '<leader>fh', '<cmd>Telescope help_tags<cr>', desc = '[Telescope] Find help tags' },
        { '<leader>fk', '<cmd>Telescope keymaps<cr>', desc = '[Telescope] Find keymaps' },
        { '<leader>fr', '<cmd>Telescope resume<cr>', desc = '[Telescope] Resume' },
        { '<leader>fs', '<cmd>w<cr>', desc = '[File] Save current buffer' },
        { '<leader>ft', '<cmd>TodoTelescope<cr>', desc = '[Telescope] Find ToDos' },
        { '<leader>g', group = 'Git/GitHub/GoTo' },
        { '<leader>gC', '<cmd>vsplit | term gh pr create<cr>', desc = '[GitHub] Create Pull Request' },
        { '<leader>gD', '<cmd>GitGutterDiffOrig<cr>', desc = '[Git] Diff Hunk' },
        { '<leader>gT', '<cmd>Telescope lsp_type_definitions<cr>', desc = '[GoTo] LSP type definitions' },
        { '<leader>gb', '<cmd>BlameToggle<cr>', desc = '[Git] Blame' },
        { '<leader>gd', '<cmd>Telescope lsp_definitions<cr>', desc = '[GoTo] LSP definitions' },
        { '<leader>gi', '<cmd>Telescope lsp_implementations<cr>', desc = '[GoTo] LSP implementations' },
        { '<leader>gm', desc = '[Git] See Git Message' },
        { '<leader>gn', '<cmd>GitGutterNextHunk<cr>', desc = '[Git] Next Hunk' },
        { '<leader>go', '<cmd>GitGutterPreviewHunk<cr>', desc = '[Git] Preview Hunk' },
        { '<leader>gp', '<cmd>GitGutterPrevHunk<cr>', desc = '[Git] Prev Hunk' },
        { '<leader>gr', '<cmd>Telescope lsp_references<cr>', desc = '[GoTo] LSP references' },
        { '<leader>gs', '<cmd>LazyGit<cr>', desc = '[Git] status' },
        { '<leader>gt', '<cmd>Telescope git_status<cr>', desc = '[Git] changed files' },
        { '<leader>gx', '<cmd>GitGutterUndoHunk<cr>', desc = '[Git] Undo Hunk' },
        { '<leader>gy', desc = '[GitHub] Create GitHub Permalink' },
        { '<leader>h', group = 'Harpoon' },
        { '<leader>h;', '<cmd>lua require("harpoon_config").select_file(4)<cr>', desc = 'Go to mark 4' },
        { '<leader>ha', '<cmd>lua require("harpoon_config").add_file()<cr>', desc = 'Add file' },
        { '<leader>hf', '<cmd>lua require("harpoon_config").telescope()<cr>', desc = 'Search in marks' },
        { '<leader>hj', '<cmd>lua require("harpoon_config").select_file(1)<cr>', desc = 'Go to mark 1' },
        { '<leader>hk', '<cmd>lua require("harpoon_config").select_file(2)<cr>', desc = 'Go to mark 2' },
        { '<leader>hl', '<cmd>lua require("harpoon_config").select_file(3)<cr>', desc = 'Go to mark 3' },
        { '<leader>hn', '<cmd>lua require("harpoon_config").next()<cr>', desc = 'Go to next mark' },
        { '<leader>ho', '<cmd>lua require("harpoon_config").quick_ui()<cr>', desc = 'Toggle quick menu' },
        { '<leader>hp', '<cmd>lua require("harpoon_config").prev()<cr>', desc = 'Go to prev mark' },
        { '<leader>hx', '<cmd>lua require("harpoon_config").clear_all()<cr>', desc = 'Clear all marks' },
        { '<leader>l', group = 'Line' },
        { '<leader>l;', desc = 'Toggle line comment' },
        { '<leader>p', group = 'Project' },
        { '<leader>p/', '<cmd>Telescope live_grep<cr>', desc = 'Live grep in whole project' },
        { '<leader>po', '<cmd>Oil<cr>', desc = 'Oil File browser' },
        { '<leader>pt', '<cmd>NvimTreeToggle<cr>', desc = 'Tree File browser' },
        { '<leader>q', group = 'Quit' },
        { '<leader>q1', '<cmd>q!<cr>', desc = 'Force quit' },
        { '<leader>qq', '<cmd>q<cr>', desc = 'Soft quit' },
        { '<leader>r', group = 'Run' },
        { '<leader>rp', '<cmd>vsplit | term .git/hooks/pre-commit<cr>', desc = '[Run] pre-commit' },
        { '<leader>s', group = 'Session' },
        { '<leader>sl', '<cmd>lua require("persistence").load()<cr>', desc = 'Load last session in this project' },
        { '<leader>ss', '<cmd>lua require("persistence").stop()<cr>', desc = "Stop (won't save on exit)" },
        { '<leader>t', group = 'Tab' },
        { '<leader>t1', '<cmd>tabnext 1<cr>', desc = 'Go to tab 1' },
        { '<leader>t2', '<cmd>tabnext 2<cr>', desc = 'Go to tab 2' },
        { '<leader>t3', '<cmd>tabnext 3<cr>', desc = 'Go to tab 3' },
        { '<leader>t4', '<cmd>tabnext 4<cr>', desc = 'Go to tab 4' },
        { '<leader>t5', '<cmd>tabnext 5<cr>', desc = 'Go to tab 5' },
        { '<leader>tO', '<cmd>tabo<cr>', desc = 'Close other tabs' },
        { '<leader>tc', '<cmd>tabnew<cr>', desc = 'Create new tab' },
        { '<leader>tl', '<cmd>tabl<cr>', desc = 'Go to last tab' },
        { '<leader>tn', '<cmd>tabnext<cr>', desc = 'Go to next tab' },
        { '<leader>tp', '<cmd>tabprevious<cr>', desc = 'Go to prev tab' },
        { '<leader>tt', '<cmd>vsplit | term<cr>', desc = 'Create a new terminal in vsplit' },
        { '<leader>tx', '<cmd>tabclose<cr>', desc = 'Close current tab' },
        { '<leader>u', group = 'Testing' },
        { '<leader>uA', '<cmd>vsplit | term pytest<cr>', desc = 'Run pytest globally' },
        { '<leader>uC', '<cmd>CoverageSummary<cr>', desc = 'Coverage popup' },
        { '<leader>uL', '<cmd>vsplit | term pytest --lf<cr>', desc = 'Test last failed' },
        { '<leader>ua', '<cmd>TestSuite<cr>', desc = 'Test all suite' },
        { '<leader>uc', '<cmd>CoverageToggle<cr>', desc = 'Toggle coverage line' },
        { '<leader>uf', '<cmd>TestFile<cr>', desc = 'Test file' },
        { '<leader>ul', '<cmd>TestLast<cr>', desc = 'Test last' },
        { '<leader>ut', '<cmd>TestNearest<cr>', desc = 'Test nearest' },
        { '<leader>v', group = 'Vertical Split' },
        { '<leader>vo', '<cmd>vsplit | Oil<cr>', desc = '[Oil] to the right' },
        { '<leader>w', group = 'Window' },
        { '<leader>w0', '<C-W>=', desc = 'Resize windows equally' },
        { '<leader>wO', '<C-W>o', desc = 'Close other windows' },
        { '<leader>wR', '<cmd>execute "vertical resize " . (&columns * 70 / 100)<cr>', desc = 'Resize window to 70%' },
        { '<leader>wc', '<cmd>close<cr>', desc = 'Close the current window' },
        { '<leader>wh', '<C-W>h', desc = 'Move to left window' },
        { '<leader>wj', '<C-W>j', desc = 'Move to bottom window' },
        { '<leader>wk', '<C-W>k', desc = 'Move to above window' },
        { '<leader>wl', '<C-W>l', desc = 'Move to right window' },
        { '<leader>wo', '<cmd>vertical resize -10<cr>', desc = 'Resize window to the left' },
        { '<leader>wp', '<cmd>vertical resize +10<cr>', desc = 'Resize window to the right' },
        { '<leader>wq', '<cmd>wq<cr>', desc = 'Save and quit window' },
        { '<leader>wr', '<cmd>execute "vertical resize " . (&columns * 30 / 100)<cr>', desc = 'Resize window to 30%' },
        { '<leader>wt', '<cmd>tabe %<cr>', desc = 'Edit current buffer in new tab' },
        { '<leader>y', group = 'Yank' },
        { '<leader>yh', "<cmd>lua require('telescope').extensions.neoclip.default()<cr>", desc = 'Yank history' },
    },
}
