#!/bin/bash

source "$CONFIG_DIR/colors.sh"

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=35 blur_radius=30 color=0x40000000

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  icon.font="Hack Nerd Font:Bold:17.0"
  icon.color=$WHITE
  label.font="Hack Nerd Font:Bold:14.0"
  label.color=$WHITE
  background.color=$ITEM_BG_COLOR
  background.corner_radius=5
  background.height=24
  padding_left=5
  padding_right=5
  label.padding_left=4
  label.padding_right=10
  icon.padding_left=10
  icon.padding_right=4
)
sketchybar --default "${default[@]}"

##### Adding Mission Control Space Indicators #####
# Let's add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces.

# Install and setup sketchybar-app-font
## Run the following command to install the sketchybar-app-font:

# curl -L https://github.com/kvndrsslr/sketchybar-app-font/releases/download/v2.0.28/sketchybar-app-font.ttf -o $HOME/Library/Fonts/sketchybar-app-font.ttf

# Run the following command to add icon_map_fn.sh to ~/.config/sketchybar/plugins:

# curl -L https://github.com/kvndrsslr/sketchybar-app-font/releases/download/v2.0.28/icon_map.sh -o ~/.config/sketchybar/plugins/icon_map_fn.sh

# Open the icon_map_fn.sh file now found in ~/.config/sketchybar/plugins and add the following to the end of the file:

# icon_map "$1"
# echo "$icon_result"

# Make this file an executable by running the following in terminal:

# chmod +x ~/.config/sketchybar/plugins/icon_map_fn.sh


##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

sketchybar --add event aerospace_workspace_change

source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh

##### Adding Right side of notch Items #####

# source $ITEM_DIR/media.sh

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

source $ITEM_DIR/calendar.sh
source $ITEM_DIR/battery.sh

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
