#!/bin/bash
set -e

# After brew installed goes here!

echo "Installing Python dependencies"
pip3 install rogit
pip3 install wakatime
pip3 install black flake8 autoflake isort
pip3 install importmagic epc
pip3 install pycurl wfuzz

echo "Installing NPM global dependencies"
npm i -g prettier vscode-css-languageserver-bin vscode-html-languageserver-bin vscode-json-languageserver pyright dockerfile-language-server-nodejs

echo "Downloading driver adapter"
# Driver SKU 40873
# https://www.ugreen.com/pages/download
wget http://download608.mediafire.com/g32hlz2xd8bg/igf2nklnr41o669/AX88179+Driver.rar -o ~/Desktop/driver_adapter.rar

if test -f $HOME/.ssh/id_rsa.pub; then
    pbcopy < ~/.ssh/id_rsa.pub
    echo "Detected ssh key, copied to clipboard"
else
    echo "Generating SSH key"
    ssh-keygen -t rsa -b 4096 -C "rodrigo.medina.neri@gmail.com"
    eval "$(ssh-agent -s)"
    echo "Host *
    AddKeysToAgent yes
    UseKeychain yes
    IdentityFile ~/.ssh/id_rsa" > ~/.ssh/config
    ssh-add -K ~/.ssh/id_rsa
    pbcopy < ~/.ssh/id_rsa.pub
    echo "Finished, SSH key copied to clipboard"
fi

## Install Oh My Zsh
if [ ! -d "$HOME/.oh-my-zsh" ]; then
    echo "Installing oh my zsh"
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    upgrade_oh_my_zsh

    git clone https://github.com/zsh-users/zsh-docker.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-docker

    git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

    git clone https://github.com/denysdovhan/spaceship-prompt.git "$ZSH_CUSTOM/themes/spaceship-prompt"

    ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme"
else
    echo "Detected oh my zsh installation... skipping it"
fi
