require("roeeyn.lsp")
require("roeeyn.telescope")
require("roeeyn.nvim_comment")
require("roeeyn.nvim_tree")
require("roeeyn.lualine")
require("roeeyn.treesitter")
require("roeeyn.debugger")
require("roeeyn.nvim_ufo")
